sudo: false
language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    # python 3.7 not natively supported yet. https://github.com/travis-ci/travis-ci/issues/9815
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "pypy"
    - python: "pypy3"
cache:
  pip: false
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - python setup.py clean --all
  - python setup.py install
script:
  - make test
  - [[ ! "$(python --version)" = "Python 3.7."* ]] || (pip install pylint==2.1.1 && make lint)
